// <auto-generated />
using System;
using CarRental.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarRental.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarRental.Models.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("About");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "Hot Wheel Car Rental şirkəti yeni yaranmasına baxmayaraq, ölkədə ən böyük avtomobil qarajına sahibdir. Bizim bütün avtomobillərimiz  bütün standartlara cavab verən, ekoloji tələblərə riayət edən yeni avtomobillərdir. Bizim şirkət avtomobil icarəsi bazarına yeni daxil olduğu üçün sərfəli qiymətlərlə digər şirkətləri üstələyir. Kirayə maşın bazarında çox şirkətin olmasına baxmayaraq keyfiyyətli və təhlükəsiz şirkət azlıq təşkil edir.",
                            HeaderDesc = "Əziz şəhərimizin qonaqları sizi “HOT WHEEL CAR RENTAL” şirkəti olaraq salamlayırıq.",
                            ImageUrl = "hero_2.jpg",
                            Title = "BİZ KİMİK"
                        });
                });

            modelBuilder.Entity("CarRental.Models.Bio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contact = "+994 55 347 08 80",
                            Email = "hwcarrental@bk.ru",
                            ImageUrl = "logo.png",
                            Location = "Nizami küçəsi 203B, AF Business House, 2-ci mərtəbə, Baku 1000, Azerbaijan",
                            WorkTime = "Bazar ertəsi-Şənbə 9:00pm - 5:00pm Bazar:Bağlıdır"
                        });
                });

            modelBuilder.Entity("CarRental.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 276, DateTimeKind.Local).AddTicks(5813),
                            ImageUrl = "mercedes.png",
                            Name = "Mercedes",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 289, DateTimeKind.Local).AddTicks(7769),
                            ImageUrl = "hyundai.png",
                            Name = "Hyundai",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 289, DateTimeKind.Local).AddTicks(8185),
                            ImageUrl = "toyota.png",
                            Name = "Toyota",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 289, DateTimeKind.Local).AddTicks(8272),
                            ImageUrl = "bmw.png",
                            Name = "BMW",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 289, DateTimeKind.Local).AddTicks(8347),
                            ImageUrl = "nissan.png",
                            Name = "Nissan",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 289, DateTimeKind.Local).AddTicks(8435),
                            ImageUrl = "mitsubishi.png",
                            Name = "Mitsubishi",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 289, DateTimeKind.Local).AddTicks(8505),
                            ImageUrl = "kia.png",
                            Name = "Kia",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 289, DateTimeKind.Local).AddTicks(8574),
                            ImageUrl = "chevrolet.png",
                            Name = "Chevrolet",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 289, DateTimeKind.Local).AddTicks(8647),
                            ImageUrl = "lexus.png",
                            Name = "Lexus",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 289, DateTimeKind.Local).AddTicks(8726),
                            ImageUrl = "tesla.png",
                            Name = "Tesla",
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("CarRental.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DailyPrice")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FuelType")
                        .HasColumnType("int");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PassengerCount")
                        .HasColumnType("int");

                    b.Property<int>("TransmissionType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 4,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 290, DateTimeKind.Local).AddTicks(9208),
                            DailyPrice = 250.0,
                            FuelType = 1,
                            ModelYear = 2012,
                            Name = "M5",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 3,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(226),
                            DailyPrice = 120.0,
                            FuelType = 2,
                            ModelYear = 2015,
                            Name = "Prado",
                            PassengerCount = 7,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 8,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(355),
                            DailyPrice = 50.0,
                            FuelType = 3,
                            ModelYear = 2013,
                            Name = "Aveo",
                            PassengerCount = 5,
                            TransmissionType = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(456),
                            DailyPrice = 50.0,
                            FuelType = 2,
                            ModelYear = 2014,
                            Name = "Accent",
                            PassengerCount = 5,
                            TransmissionType = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 2,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(550),
                            DailyPrice = 85.0,
                            FuelType = 1,
                            ModelYear = 2013,
                            Name = "Azera",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            ColorId = 4,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(658),
                            DailyPrice = 55.0,
                            FuelType = 1,
                            ModelYear = 2015,
                            Name = "Elantra",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(751),
                            DailyPrice = 140.0,
                            FuelType = 2,
                            ModelYear = 2014,
                            Name = "H1",
                            PassengerCount = 9,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 2,
                            ColorId = 4,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(848),
                            DailyPrice = 65.0,
                            FuelType = 1,
                            ModelYear = 2014,
                            Name = "Ix35",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 2,
                            ColorId = 4,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(940),
                            DailyPrice = 70.0,
                            FuelType = 2,
                            ModelYear = 2013,
                            Name = "Sonata",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 2,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(1049),
                            DailyPrice = 75.0,
                            FuelType = 1,
                            ModelYear = 2017,
                            Name = "Sonata",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 7,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(1142),
                            DailyPrice = 55.0,
                            FuelType = 1,
                            ModelYear = 2014,
                            Name = "Cerato",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 7,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(1236),
                            DailyPrice = 75.0,
                            FuelType = 1,
                            ModelYear = 2014,
                            Name = "Optima",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 7,
                            ColorId = 4,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(1327),
                            DailyPrice = 50.0,
                            FuelType = 2,
                            ModelYear = 2014,
                            Name = "Rio",
                            PassengerCount = 5,
                            TransmissionType = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 7,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(1420),
                            DailyPrice = 90.0,
                            FuelType = 2,
                            ModelYear = 2013,
                            Name = "Sorento",
                            PassengerCount = 7,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 7,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(1516),
                            DailyPrice = 65.0,
                            FuelType = 2,
                            ModelYear = 2014,
                            Name = "Sportage",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 9,
                            ColorId = 1,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(1611),
                            DailyPrice = 200.0,
                            FuelType = 1,
                            ModelYear = 2012,
                            Name = "LX570",
                            PassengerCount = 7,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 1,
                            ColorId = 1,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(1700),
                            DailyPrice = 350.0,
                            FuelType = 1,
                            ModelYear = 2012,
                            Name = "G-class",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 1,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(2063),
                            DailyPrice = 400.0,
                            FuelType = 1,
                            ModelYear = 2015,
                            Name = "G-class",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 1,
                            ColorId = 1,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(2186),
                            DailyPrice = 350.0,
                            FuelType = 2,
                            ModelYear = 2016,
                            Name = "S-class",
                            PassengerCount = 4,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 1,
                            ColorId = 1,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(2284),
                            DailyPrice = 450.0,
                            FuelType = 2,
                            ModelYear = 2016,
                            Name = "V-class",
                            PassengerCount = 6,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 6,
                            ColorId = 1,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(2381),
                            DailyPrice = 80.0,
                            FuelType = 2,
                            ModelYear = 2013,
                            Name = "L200",
                            PassengerCount = 5,
                            TransmissionType = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 6,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(2484),
                            DailyPrice = 85.0,
                            FuelType = 1,
                            ModelYear = 2013,
                            Name = "Pajero",
                            PassengerCount = 7,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 5,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(2580),
                            DailyPrice = 90.0,
                            FuelType = 2,
                            ModelYear = 2013,
                            Name = "Navara",
                            PassengerCount = 5,
                            TransmissionType = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 5,
                            ColorId = 4,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(2675),
                            DailyPrice = 50.0,
                            FuelType = 1,
                            ModelYear = 2014,
                            Name = "Sunny",
                            PassengerCount = 5,
                            TransmissionType = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 3,
                            ColorId = 4,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(2767),
                            DailyPrice = 90.0,
                            FuelType = 1,
                            ModelYear = 2013,
                            Name = "Camry",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 3,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(2858),
                            DailyPrice = 160.0,
                            FuelType = 1,
                            ModelYear = 2014,
                            Name = "Land Cruiser",
                            PassengerCount = 7,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 3,
                            ColorId = 4,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(2948),
                            DailyPrice = 300.0,
                            FuelType = 1,
                            ModelYear = 2018,
                            Name = "Land Cruiser",
                            PassengerCount = 7,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 4,
                            ColorId = 3,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(3041),
                            DailyPrice = 200.0,
                            FuelType = 1,
                            ModelYear = 2011,
                            Name = "X5",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 3,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(3133),
                            DailyPrice = 200.0,
                            FuelType = 1,
                            ModelYear = 2018,
                            Name = "Prado",
                            PassengerCount = 7,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 30,
                            BrandId = 10,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(3229),
                            DailyPrice = 250.0,
                            FuelType = 4,
                            ModelYear = 2016,
                            Name = "X",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 31,
                            BrandId = 10,
                            ColorId = 5,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(3327),
                            DailyPrice = 270.0,
                            FuelType = 4,
                            ModelYear = 2018,
                            Name = "S",
                            PassengerCount = 4,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 32,
                            BrandId = 10,
                            ColorId = 4,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(3426),
                            DailyPrice = 250.0,
                            FuelType = 4,
                            ModelYear = 2017,
                            Name = "3",
                            PassengerCount = 4,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 33,
                            BrandId = 5,
                            ColorId = 6,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 291, DateTimeKind.Local).AddTicks(3518),
                            DailyPrice = 70.0,
                            FuelType = 4,
                            ModelYear = 2017,
                            Name = "Leaf",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("CarRental.Models.CarImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            ImageUrl = "bmw-m5.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            ImageUrl = "bmw-x5.png",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3,
                            ImageUrl = "chevrolet-aveo-2013.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CarId = 4,
                            ImageUrl = "hyundai-accent-2014.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CarId = 5,
                            ImageUrl = "hyundai-azera-2013.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CarId = 6,
                            ImageUrl = "hyundai-elantra-2015.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            CarId = 7,
                            ImageUrl = "hyundai-h1-2014.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            CarId = 8,
                            ImageUrl = "hyundai-ix35-2014.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            CarId = 9,
                            ImageUrl = "hyundai-sonata-2013.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            CarId = 10,
                            ImageUrl = "hyundai-sonata-2017.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            CarId = 11,
                            ImageUrl = "kia-cerato-2014.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 12,
                            CarId = 12,
                            ImageUrl = "kia-optima-2014.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 13,
                            CarId = 13,
                            ImageUrl = "kia-rio-2014.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 14,
                            CarId = 14,
                            ImageUrl = "kia-sorento-2013.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 15,
                            CarId = 15,
                            ImageUrl = "kia-sportage-2014.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 16,
                            CarId = 16,
                            ImageUrl = "lexus-570-2012.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 17,
                            CarId = 17,
                            ImageUrl = "mercedes-g-class-2012.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 18,
                            CarId = 18,
                            ImageUrl = "mercedes-g-class-2015.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 19,
                            CarId = 19,
                            ImageUrl = "mercedes-s-class-2016.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 20,
                            CarId = 20,
                            ImageUrl = "mercedes-v-class-2016.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 21,
                            CarId = 21,
                            ImageUrl = "mitsubishi-L200-2013.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 22,
                            CarId = 22,
                            ImageUrl = "mitsubishi-pajero.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 23,
                            CarId = 23,
                            ImageUrl = "nissan-navara-2013.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 24,
                            CarId = 24,
                            ImageUrl = "nissan-sunny-2014.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 25,
                            CarId = 25,
                            ImageUrl = "toyota-camry-2013.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 26,
                            CarId = 26,
                            ImageUrl = "toyota-land-cruiser-2014.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 27,
                            CarId = 27,
                            ImageUrl = "toyota-land-cruiser-2018.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 28,
                            CarId = 28,
                            ImageUrl = "toyota-prado-2015.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 29,
                            CarId = 29,
                            ImageUrl = "toyota-prado-2018.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 30,
                            CarId = 30,
                            ImageUrl = "tesla-x-2016.png",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 31,
                            CarId = 31,
                            ImageUrl = "tesla-s-2018.png",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 32,
                            CarId = 32,
                            ImageUrl = "tesla-3-2017.png",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 33,
                            CarId = 33,
                            ImageUrl = "nissan-leaf-2017.png",
                            IsMain = true,
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("CarRental.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 290, DateTimeKind.Local).AddTicks(1123),
                            Name = "Qara",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 290, DateTimeKind.Local).AddTicks(1758),
                            Name = "Ağ",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 290, DateTimeKind.Local).AddTicks(1872),
                            Name = "Qəhvəyi",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 290, DateTimeKind.Local).AddTicks(1961),
                            Name = "Boz",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 290, DateTimeKind.Local).AddTicks(2049),
                            Name = "Qırmızı",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 290, DateTimeKind.Local).AddTicks(2345),
                            Name = "Mavi",
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("CarRental.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("isPaid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("CarRental.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 301, DateTimeKind.Local).AddTicks(5424),
                            ImageUrl = "murad.jpg",
                            Name = "Murad",
                            Position = "CEO",
                            Surname = "Vəliyev",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 301, DateTimeKind.Local).AddTicks(6508),
                            ImageUrl = "rashid.jpg",
                            Name = "Rəşid",
                            Position = "CFO",
                            Surname = "Məmməmdov",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 301, DateTimeKind.Local).AddTicks(6637),
                            ImageUrl = "farid.jpg",
                            Name = "Fərid",
                            Position = "Developer",
                            Surname = "Balıyev",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 301, DateTimeKind.Local).AddTicks(6735),
                            ImageUrl = "umud.jpg",
                            Name = "Umud",
                            Position = "Mütəxəssis",
                            Surname = "Umudov",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 301, DateTimeKind.Local).AddTicks(6824),
                            ImageUrl = "samir.jpg",
                            Name = "Samir",
                            Position = "Mütəxəssis",
                            Surname = "Əmiraslanov",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 10, 29, 5, 6, 13, 301, DateTimeKind.Local).AddTicks(6924),
                            ImageUrl = "orxan.jpg",
                            Name = "Orxan",
                            Position = "Mütəxəssis",
                            Surname = "Qəhrəmanov",
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("CarRental.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("CarRental.Models.Car", b =>
                {
                    b.HasOne("CarRental.Models.Brand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRental.Models.Color", "Color")
                        .WithMany("Cars")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarRental.Models.CarImage", b =>
                {
                    b.HasOne("CarRental.Models.Car", "Car")
                        .WithMany("CarImages")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarRental.Models.Rental", b =>
                {
                    b.HasOne("CarRental.Models.Car", "Car")
                        .WithMany("Rentals")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRental.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CarRental.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CarRental.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRental.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CarRental.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
