// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentACarProject.Data;

namespace RentACarProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220910053027_AddSeedChanges")]
    partial class AddSeedChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("RentACarProject.Entity.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 221, DateTimeKind.Local).AddTicks(950),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "mercedes.png",
                            Name = "Mercedes",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 228, DateTimeKind.Local).AddTicks(4669),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "hyundai.png",
                            Name = "Hyundai",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 228, DateTimeKind.Local).AddTicks(5175),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "toyota.png",
                            Name = "Toyota",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 228, DateTimeKind.Local).AddTicks(5309),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "bmw.png",
                            Name = "BMW",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 228, DateTimeKind.Local).AddTicks(5647),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "nissan.png",
                            Name = "Nissan",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 228, DateTimeKind.Local).AddTicks(5891),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "mitsubishi.png",
                            Name = "Mitsubishi",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 228, DateTimeKind.Local).AddTicks(6256),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "kia.png",
                            Name = "Kia",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 228, DateTimeKind.Local).AddTicks(6353),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "chevrolet.png",
                            Name = "Chevrolet",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 228, DateTimeKind.Local).AddTicks(6439),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "lexus.png",
                            Name = "Lexus",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("RentACarProject.Entity.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DailyPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuelType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PassengerCount")
                        .HasColumnType("int");

                    b.Property<string>("TransmissionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 4,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(6082),
                            DailyPrice = 250.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ModelYear = 2012,
                            Name = "M5",
                            PassengerCount = 5,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 4,
                            ColorId = 3,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(6790),
                            DailyPrice = 200.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ModelYear = 2011,
                            Name = "X5",
                            PassengerCount = 5,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 8,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(6955),
                            DailyPrice = 50.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ModelYear = 2013,
                            Name = "Aveo",
                            PassengerCount = 5,
                            TransmissionType = "Manual",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(7046),
                            DailyPrice = 50.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ModelYear = 2014,
                            Name = "Accent",
                            PassengerCount = 5,
                            TransmissionType = "Manual",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 2,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(7132),
                            DailyPrice = 85.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ModelYear = 2013,
                            Name = "Azera",
                            PassengerCount = 5,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            ColorId = 4,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(7234),
                            DailyPrice = 55.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ModelYear = 2015,
                            Name = "Elantra",
                            PassengerCount = 5,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(7321),
                            DailyPrice = 140.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Diesel",
                            ModelYear = 2014,
                            Name = "H1",
                            PassengerCount = 9,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 2,
                            ColorId = 4,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(7399),
                            DailyPrice = 65.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ModelYear = 2014,
                            Name = "Ix35",
                            PassengerCount = 5,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 2,
                            ColorId = 4,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(7485),
                            DailyPrice = 70.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Diesel",
                            ModelYear = 2013,
                            Name = "Sonata",
                            PassengerCount = 5,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 2,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(7585),
                            DailyPrice = 75.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ModelYear = 2017,
                            Name = "Sonata",
                            PassengerCount = 5,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 7,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(7673),
                            DailyPrice = 55.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ModelYear = 2014,
                            Name = "Cerato",
                            PassengerCount = 5,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 7,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(7762),
                            DailyPrice = 75.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ModelYear = 2014,
                            Name = "Optima",
                            PassengerCount = 5,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 7,
                            ColorId = 4,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(7958),
                            DailyPrice = 50.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Diesel",
                            ModelYear = 2014,
                            Name = "Rio",
                            PassengerCount = 5,
                            TransmissionType = "Manual",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 7,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(8062),
                            DailyPrice = 90.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Diesel",
                            ModelYear = 2013,
                            Name = "Sorento",
                            PassengerCount = 7,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 7,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(8143),
                            DailyPrice = 65.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ModelYear = 2014,
                            Name = "Sportage",
                            PassengerCount = 5,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 9,
                            ColorId = 1,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(8229),
                            DailyPrice = 200.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ModelYear = 2012,
                            Name = "LX570",
                            PassengerCount = 7,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 1,
                            ColorId = 1,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(8312),
                            DailyPrice = 350.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ModelYear = 2012,
                            Name = "G-class",
                            PassengerCount = 5,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 1,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(8413),
                            DailyPrice = 400.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ModelYear = 2015,
                            Name = "G-class",
                            PassengerCount = 5,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 1,
                            ColorId = 1,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(8499),
                            DailyPrice = 350.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Diesel",
                            ModelYear = 2016,
                            Name = "S-class",
                            PassengerCount = 4,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 1,
                            ColorId = 1,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(8585),
                            DailyPrice = 450.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Diesel",
                            ModelYear = 2016,
                            Name = "V-class",
                            PassengerCount = 6,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 6,
                            ColorId = 1,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(8665),
                            DailyPrice = 80.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Diesel",
                            ModelYear = 2013,
                            Name = "L200",
                            PassengerCount = 5,
                            TransmissionType = "Manual",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 6,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(8756),
                            DailyPrice = 85.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ModelYear = 2013,
                            Name = "Pajero",
                            PassengerCount = 7,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 5,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(8841),
                            DailyPrice = 90.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Diesel",
                            ModelYear = 2013,
                            Name = "Navara",
                            PassengerCount = 5,
                            TransmissionType = "Manual",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 5,
                            ColorId = 4,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(8933),
                            DailyPrice = 50.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ModelYear = 2014,
                            Name = "Sunny",
                            PassengerCount = 5,
                            TransmissionType = "Manual",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 3,
                            ColorId = 4,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(9019),
                            DailyPrice = 90.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ModelYear = 2013,
                            Name = "Camry",
                            PassengerCount = 5,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 3,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(9116),
                            DailyPrice = 160.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ModelYear = 2014,
                            Name = "Land Cruiser",
                            PassengerCount = 7,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 3,
                            ColorId = 4,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(9200),
                            DailyPrice = 300.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ModelYear = 2018,
                            Name = "Land Cruiser",
                            PassengerCount = 7,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 3,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(9289),
                            DailyPrice = 120.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Diesel",
                            ModelYear = 2015,
                            Name = "Prado",
                            PassengerCount = 7,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 3,
                            ColorId = 2,
                            CreatedAt = new DateTime(2022, 9, 10, 9, 30, 25, 229, DateTimeKind.Local).AddTicks(9373),
                            DailyPrice = 200.0,
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ModelYear = 2018,
                            Name = "Prado",
                            PassengerCount = 7,
                            TransmissionType = "Auto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("RentACarProject.Entity.CarImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            ImageUrl = "bmw-m5.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            ImageUrl = "bmw-x5.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3,
                            ImageUrl = "chevrolet-aveo-2013.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CarId = 4,
                            ImageUrl = "hyundai-accent-2014.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CarId = 5,
                            ImageUrl = "hyundai - azera - 2013.jpg"
                        },
                        new
                        {
                            Id = 6,
                            CarId = 6,
                            ImageUrl = "hyundai - elantra - 2015.jpg"
                        },
                        new
                        {
                            Id = 7,
                            CarId = 7,
                            ImageUrl = "hyundai-h1-2014.jpg"
                        },
                        new
                        {
                            Id = 8,
                            CarId = 8,
                            ImageUrl = "hyundai-ix35-2014.jpg"
                        },
                        new
                        {
                            Id = 9,
                            CarId = 9,
                            ImageUrl = "hyundai-sonata-2013.jpg"
                        },
                        new
                        {
                            Id = 10,
                            CarId = 10,
                            ImageUrl = "hyundai-sonata-2017.jpg"
                        },
                        new
                        {
                            Id = 11,
                            CarId = 11,
                            ImageUrl = "kia-cerato-2014.jpg"
                        },
                        new
                        {
                            Id = 12,
                            CarId = 12,
                            ImageUrl = "kia-optima-2014.jpg"
                        },
                        new
                        {
                            Id = 13,
                            CarId = 13,
                            ImageUrl = "kia-rio-2014.jpg"
                        },
                        new
                        {
                            Id = 14,
                            CarId = 14,
                            ImageUrl = "kia-sorento-2013.jpg"
                        },
                        new
                        {
                            Id = 15,
                            CarId = 15,
                            ImageUrl = "kia-sportage-2014.jpg"
                        },
                        new
                        {
                            Id = 16,
                            CarId = 16,
                            ImageUrl = "lexus-570-2012.jpg"
                        },
                        new
                        {
                            Id = 17,
                            CarId = 17,
                            ImageUrl = "mercedes-g-class-2012.jpg"
                        },
                        new
                        {
                            Id = 18,
                            CarId = 18,
                            ImageUrl = "mercedes-g-class-2015.jpg"
                        },
                        new
                        {
                            Id = 19,
                            CarId = 19,
                            ImageUrl = "mercedes-s-class-2016.jpg"
                        },
                        new
                        {
                            Id = 20,
                            CarId = 20,
                            ImageUrl = "mercedes-v-class-2016.jpg"
                        },
                        new
                        {
                            Id = 21,
                            CarId = 21,
                            ImageUrl = "mitsubishi-L200-2013.jpg"
                        },
                        new
                        {
                            Id = 22,
                            CarId = 22,
                            ImageUrl = "mitsubishi-pajero.jpg"
                        },
                        new
                        {
                            Id = 23,
                            CarId = 23,
                            ImageUrl = "nissan-navara-2013.jpg"
                        },
                        new
                        {
                            Id = 24,
                            CarId = 24,
                            ImageUrl = "nissan-sunny-2014.jpg"
                        },
                        new
                        {
                            Id = 25,
                            CarId = 25,
                            ImageUrl = "toyota-camry-2013.jpg"
                        },
                        new
                        {
                            Id = 26,
                            CarId = 26,
                            ImageUrl = "toyota-land-cruiser-2014.jpg"
                        },
                        new
                        {
                            Id = 27,
                            CarId = 27,
                            ImageUrl = "toyota-land-cruiser-2018.jpg"
                        },
                        new
                        {
                            Id = 28,
                            CarId = 28,
                            ImageUrl = "toyota-prado-2015.jpg"
                        },
                        new
                        {
                            Id = 29,
                            CarId = 29,
                            ImageUrl = "toyota-prado-2018.jpg"
                        });
                });

            modelBuilder.Entity("RentACarProject.Entity.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "black"
                        },
                        new
                        {
                            Id = 2,
                            Name = "white"
                        },
                        new
                        {
                            Id = 3,
                            Name = "brown"
                        },
                        new
                        {
                            Id = 4,
                            Name = "grey"
                        });
                });

            modelBuilder.Entity("RentACarProject.Entity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RentACarProject.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RentACarProject.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentACarProject.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RentACarProject.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RentACarProject.Entity.Car", b =>
                {
                    b.HasOne("RentACarProject.Entity.Brand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentACarProject.Entity.Color", "Color")
                        .WithMany("Cars")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RentACarProject.Entity.CarImage", b =>
                {
                    b.HasOne("RentACarProject.Entity.Car", "Car")
                        .WithMany("CarImages")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
